// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pudwgzutzoidxbvozhnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1ZHdnenV0em9pZHhidm96aG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDg4NzQsImV4cCI6MjA2NTQ4NDg3NH0.kh_J0YvR52AkzSdajkyjGyae1W9NRD_Av4EGqQtS6Xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});